name: gittop
title: GitTop
version: git
summary: Lightweight desktop client for GitHub notifications
description: |
  GitTop is a lightweight desktop client for GitHub notifications.
  Why spin up a browser just to check your GitHub notifications?

  Features:
  - Super lean: ~5-15MB RAM whilst in use (1-2MB in tray)
  - Multi-account: Seamless support for multiple GitHub accounts
  - Smart Rules: Powerful engine for priorities and hiding noisy notifications
  - Cross platform: Native experience on Windows and Linux
  - Dual Mode: Minimalist by default, Power Mode for advanced features

license: AGPL-3.0-only
contact: https://github.com/AmarBego/GitTop/issues
issues: https://github.com/AmarBego/GitTop/issues
source-code: https://github.com/AmarBego/GitTop
website: https://amarbego.github.io/GitTop/

grade: stable
confinement: strict
base: core24

platforms:
  amd64:

apps:
  gittop:
    command: bin/gittop
    desktop: share/applications/gittop.desktop
    extensions: [gnome]
    plugs:
      - network
      - network-status
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - gsettings
      - home
      - password-manager-service

parts:
  gittop:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev
      - libdbus-1-dev
    stage-packages:
      - libssl3
      - libdbus-1-3
    override-build: |
      craftctl default
      # Install desktop file
      install -Dm644 src/platform/resources/gittop.desktop $CRAFT_PART_INSTALL/share/applications/gittop.desktop
      # Install icon
      install -Dm644 assets/images/GitTop-256x256.png $CRAFT_PART_INSTALL/share/icons/hicolor/256x256/apps/gittop.png
